# Use this file to create an environment using:
# conda env create -f requirements.yaml

# Use this file to create an environment using:
# conda env create -f requirements.yaml

name: coffeeleafinfuses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - jupyter
  - notebook
  - pandas
  - omegaconf
  - jupyter_server
  - numpy
  - scipy
  - scikit-learn
  - scikit-bio
  - matplotlib
  - seaborn
  - requests
  - pip
  - pip:
    - mca
    - pyyaml