# Use this file to create an environment using:
# conda env create -f requirements.yaml

name: coffeeleafinfuses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - ipykernel
  - numpy
  - pandas=2.2.3
  - biopython=1.81
  - openpyxl<4.0.0
  - omegaconf=2.3.0
  - requests=2.31.0
  - tenacity=9.0.0
  - pyyaml=6.0.2
  - pybliometrics=4.1
  - pip=21.3.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.4.2
  - networkx=3.2.1
  - statsmodels=0.14.1
  - scipy=1.11.4
  - scikit-bio=0.7.0
  - pip
  - pip:
    - prince==0.7.1